name: My First CI Pipeline

on:
  push:

jobs:
  check:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check HTML file
        run: Test-Path index.html
    
      - name: Check CSS file
        run: Test-Path style.css
    
      - name: Check JavaScript file
        run: Test-Path script.js